pipeline {
    agent any
    tools {
        maven 'Maven-3'
    }
    stages {
        stage('Clean') {
            steps {
                git url: 'https://github.com/salvadorcuray/empty-login.git', branch: 'master'   
                sh 'mvn clean'
            }
        }
        stage('Deploy') {
            when {
                expression {
                    currentBuild.result == null || currentBuild.result == 'SUCCESS' 
                }
            }
            steps {
                sh 'mv deploy '
            }
        }
    }
}

