
pipeline {
        agent any
        tools {
            maven 'MAVEN3'
        }
        stages {
            stage('Build') {
                steps {
                    git url: 'https://github.com/salvadorcuray/empty-login.git', branch: 'develop', credentialsId:'github-credential'
                    sh 'mvn clean compile'
                }
            }
            stage("SonarQube analysis") {
                steps {
                    withSonarQubeEnv('sonarqube_devops') {
                        sh 'mvn verify sonar:sonar -Dsonar.host.url=http://sonarqube_devops:9000'
                    }
                }
            }
            stage("Quality Gate") {
                steps {
                    timeout(time: 1, unit: 'HOURS') {
                        waitForQualityGate abortPipeline: true
                    }
                }
            }
        }
}