
pipeline {
        agent any
        tools {
            maven 'MAVEN3'
        }
        stages {
            stage("build & SonarQube analysis") {
                steps {
                    git url: 'https://github.com/salvadorcuray/empty-login.git', branch: 'develop', credentialsId:'github-credential'
                    withSonarQubeEnv('sonarqube_devops') {
                        sh 'mvn clean package sonar:sonar'
                    }
                }
            }
            stage("Quality Gate") {
                steps {
                    timeout(time: 1, unit: 'HOURS') {
                        waitForQualityGate abortPipeline: true
                    }
                }
            }
        }
}